### ISSUE TITLE
TRIAN.PY  Problem

### ISSUE THREAD

**Issue by leishi2018** [sagieppel/Fully-convolutional-neural-network-FCN-for-semantic-segmentation-Tensorflow-implementation#9]
Hello, I meet this issues that I take my own RGB test picture and PNG labels .but it comes this
(and RGB test picture are not the same size)

ResourceExhaustedError (see above for traceback): OOM when allocating tensor of shape [7,7,512,4096] and type float[[Node: W6/Adam/Initializer/zeros = Const[_class=["loc:@W6"], dtype=DT_FLOAT, value=Tensor<type: float shape: [7,7,512,4096] values: [[[0 0 0]]]...>, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by sagieppel** [comment]
Out of memory issue.
Use a smaller image.
Smaller batch size.
Larger GPU
or other lighter network,
